[package]
name = "cang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
crossterm = "0.28.1"
env_logger = "0.11.5"
log = "0.4.22"
ratatui = "0.29.0"
serde = "1.0.215"
serde_yaml = "0.9.34"
tokio = "1.41.1"
